from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader  # swap per file type
from src.milvus_client import get_collection, get_embedder

def load_and_chunk(filepath: str, chunk_size: int = 800, chunk_overlap: int = 100):
    loader = PyPDFLoader(filepath)
    docs = loader.load()
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,      # smaller than your vanilla RAG chunk size on purpose
        chunk_overlap=chunk_overlap,
    )
    chunks = splitter.split_documents(docs)

    print(f"{filepath}: {len(docs)} pages -> {len(chunks)} extraction-ready chunks")
    return chunks


# --- Phase 1: Milvus ingestion additions below ---
# load_and_chunk above is untouched — this reuses its output, it doesn't
# replace or touch whatever function feeds chunks into LLMGraphTransformer
# for the graph side. Call this as a separate, additive step.

# def embed_and_ingest(chunks, source: str):
#     """
#     Embeds chunk texts and inserts them into Milvus.
#     Call this with the same chunks you already feed to graph_builder.py —
#     same source documents, second storage backend, nothing shared or
#     overwritten.
#     """
#     collection = get_collection()
#     embedder = get_embedder()

#     texts = [c.page_content for c in chunks]
#     embeddings = embedder.encode(texts, show_progress_bar=True).tolist()
#     sources = [source] * len(texts)

#     collection.insert([texts, sources, embeddings])
#     collection.flush()
#     print(f"[ingest] {source}: inserted {len(texts)} chunks into Milvus")

def embed_and_ingest(
    chunks,
    document_id: str,
    filename: str,
    source_key: str,
):
    texts = [chunk.page_content for chunk in chunks]
    collection = get_collection()
    # Generate embeddings
    embeddings = get_embedder().encode(
        texts,
        normalize_embeddings=True,
    ).tolist()

    # Metadata for every chunk
    document_ids = [document_id] * len(chunks)

    chunk_ids = [
        f"{document_id}_{i}"
        for i in range(len(chunks))
    ]

    filenames = [filename] * len(chunks)

    source_keys = [source_key] * len(chunks)

    page_numbers = [
        chunk.metadata.get("page", 0)
        for chunk in chunks
    ]

    # id is auto-generated by Milvus, so we don't insert it.
    data = [
        document_ids,
        chunk_ids,
        filenames,
        source_keys,
        page_numbers,
        texts,
        embeddings,
    ]

    collection.insert(data)
    collection.flush()

def ingest_file_to_milvus(
    filepath,
    document_id,
    filename,
    source_key,
):
    chunks = load_and_chunk(filepath)

    embed_and_ingest(
        chunks=chunks,
        document_id=document_id,
        filename=filename,
        source_key=source_key,
    )

    return chunks

# if __name__ == "__main__":
#     import sys
#     if len(sys.argv) < 2:
#         print("Usage: python -m src.ingest <filepath>")
#         sys.exit(1)
#     ingest_file_to_milvus(sys.argv[1])