import os
from langchain_text_splitters import RecursiveCharacterTextSplitter
from src.preprocessing.mineru_processor import mineru_to_documents
from src.preprocessing.document_processor import process_document
from src.storage.milvus_client import get_collection, get_embedder


def load_and_chunk(
    filepath: str,
    chunk_size: int = 800,
    chunk_overlap: int = 100,
):
    """
    Prepare a supported document and split it into chunks.

    PDF:processed page-by-page with MinerU.
    DOCX:Converted to PDF, then processed page-by-page with MinerU.
    PPTX/XLSX:extracted directly into LangChain Documents.
    """

    processed = process_document(filepath)

    if processed["type"] == "mineru":
        docs, _ = mineru_to_documents(
            processed["path"]
        )

        # Remove the temporary DOCX-generated PDF.
        if processed["temporary_pdf"]:
            try:
                os.remove(processed["path"])
            except OSError:
                pass

    else:
        docs = processed["documents"]

    return chunk_documents(
        docs,
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
    )

def chunk_documents(
    docs,
    chunk_size: int = 800,
    chunk_overlap: int = 100,
):
    """
    Split already-processed page Documents into chunks.
    """

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
    )

    chunks = splitter.split_documents(docs)

    print(
        f"{len(docs)} pages -> "
        f"{len(chunks)} extraction-ready chunks"
    )

    return chunks

def embed_and_ingest(
    chunks,
    document_id: str,
    filename: str,
    source_key: str,
):
    texts = [chunk.page_content for chunk in chunks]
    collection = get_collection()
    # Generate embeddings
    embeddings = get_embedder().encode(
        texts,
        normalize_embeddings=True,
    ).tolist()

    # Metadata for every chunk
    document_ids = [document_id] * len(chunks)

    chunk_ids = [
        f"{document_id}_{i}"
        for i in range(len(chunks))
    ]

    filenames = [filename] * len(chunks)

    source_keys = [source_key] * len(chunks)

    page_numbers = [
        chunk.metadata.get("page", 0)
        for chunk in chunks
    ]

    # id is auto-generated by Milvus, so we don't insert it.
    data = [
        document_ids,
        chunk_ids,
        filenames,
        source_keys,
        page_numbers,
        texts,
        embeddings,
    ]

    collection.insert(data)
    collection.flush()

def ingest_file_to_milvus(
    filepath,
    document_id,
    filename,
    source_key,
):
    chunks = load_and_chunk(filepath)

    embed_and_ingest(
        chunks=chunks,
        document_id=document_id,
        filename=filename,
        source_key=source_key,
    )

    return chunks